language: generic
sudo: required
services:
  - docker

before_install:
  - echo 'before_install'
  - docker build -t daiboom/react-test-app -f ./frontend/Dockerfile.dev
    ./frontend

script:
  - docker run -e CI=true daiboom/react-test-app npm run test

after_success:
  - echo 'after_success'
  - docker build -t daiboom/docker-frontend ./frontend
  - docker build -t daiboom/docker-backend  ./backend
  - docker build -t daiboom/docker-nginx    ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID"
    --password-stdin

  - docker push daiboom/docker-frontend
  - docker push daiboom/docker-backend
  - docker push daiboom/docker-nginx
